title: Orycion
tagline: We build products.
url: https://www.orycion.com

plugins:
  - jekyll-remote-theme

remote_theme: sziv2p/jekyll-theme-scaffold

google_analytics: UA-157030898-1

collections:
  - products
