title: Orycion
tagline: We design and build digital products, feel free to contact us for more information.
url: https://www.orycion.com

plugins:
  - jekyll-remote-theme

remote_theme: sziv2p/jekyll-theme-scaffold

google_analytics: UA-157030898-1

collections:
  - products
